version: '3.9'
services:
  php-env:
    build:
      context: .  
      dockerfile: Dockerfile 
    volumes:
      - ./src:/var/www/html
    ports:
      - 8081:80
    depends_on:
      - mysql_db
  mysql_db:
    image: mysql:latest
    command: --default-authentication-plugin=mysql_native_password
    restart: always
    environment:
      MYSQL_USER: root
      MYSQL_DATABASE:  notes_db_vk
      MYSQL_PASSWORD: null
      MYSQL_ALLOW_EMPTY_PASSWORD: true
      MYSQL_ROOT_HOST: '%'
      
  phpmyadmin:
    image: phpmyadmin:latest
    restart: always
    ports:
      - 9000:80
    environment:
      PMA_ARBITRARY: 1
    depends_on:
      - mysql_db